update

diff --git a/autoload/commands/__check__ b/autoload/commands/__check__
--- a/autoload/commands/__check__
+++ b/autoload/commands/__check__
@@ -1,10 +1,11 @@
 #!/bin/zsh
 
 __import "core/core"
-__import "job/spinner"
 __import "print/print"
+__import "job/spinner"
 
-local    line is_verbose=false
+local    is_verbose=false
+local    line
 local -A zspec
 local -a fail args
 
@@ -25,18 +26,48 @@ do
     shift
 done
 
+exists() {
+    local from dir
+
+    from="$1"
+    dir="$2"
+    case "$from" in
+        "local")
+            return 0
+            ;;
+        "oh-my-zsh")
+            if [[ -d ${dir:h} ]]; then
+                return 0
+            fi
+            ;;
+        *)
+            if [[ -d $dir ]]; then
+                return 0
+            fi
+            ;;
+    esac
+
+    return 1
+}
+
 for line in ${(u)${args[@]:gs:@::}}
 do
     zspec=( ${(@f)"$(__parser__ "$line")"} )
-    [[ $zspec[from] == "local" ]] && continue
-    if [[ $zspec[from] != "oh-my-zsh" && ! -e $zspec[dir] ]] || [[ $zspec[from] == "oh-my-zsh" && ! -d ${zspec[dir]:h} ]]; then
+    if [[ $zspec[from] == "local" ]]; then
+        continue
+    fi
+    if ! exists "$zspec[from]" "$zspec[dir]"; then
         fail+=("$zspec[name]")
     fi
+    # if [[ $zspec[from] != "oh-my-zsh" && ! -e $zspec[dir] ]] || [[ $zspec[from] == "oh-my-zsh" && ! -d ${zspec[dir]:h} ]]; then
+    #     fail+=("$zspec[name]")
+    # fi
 done
 
 if (( $#fail > 0 )); then
     if $is_verbose; then
-        __put "- \033[31m%s\033[m: not installed\n" "${(@nO)fail}"
+        # __put "- \033[31m%s\033[m: not installed\n" "${(@nO)fail}"
+        __put "- $fg[red]%s$reset_color: not installed\n" "${(@nO)fail}"
     fi
     return 1
 else
